"""Obsidian vault adapter (architecture §25, INV-9).

Writes human-readable notes into the Obsidian vault (``vault-trading/`` by
default). The vault is a plain directory; the adapter never touches secrets and
marks autogenerated content (the note renderer embeds the header).
"""

from __future__ import annotations

from pathlib import Path
from typing import Protocol

__all__ = ["FileVaultWriter", "MemoryVaultWriter", "NullVaultWriter", "VaultWriter"]


class VaultWriter(Protocol):
    """Write-one-note boundary for the Obsidian vault."""

    def write_note(self, relative_path: str, content: str) -> str:
        """Persist one note; returns the vault-relative path written."""
        ...


class FileVaultWriter:
    """Filesystem vault writer (UTF-8, parent directories created as needed)."""

    def __init__(self, base_dir: str | Path, *, create: bool = True) -> None:
        self._base_dir = Path(base_dir)
        if create:
            self._base_dir.mkdir(parents=True, exist_ok=True)
        elif not self._base_dir.is_dir():
            raise FileNotFoundError(f"vault base directory does not exist: {self._base_dir}")

    @property
    def base_dir(self) -> Path:
        return self._base_dir

    def write_note(self, relative_path: str, content: str) -> str:
        target = (self._base_dir / relative_path).resolve()
        if self._base_dir.resolve() not in target.parents:
            raise ValueError(f"note path escapes the vault: {relative_path}")
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")
        return relative_path


class MemoryVaultWriter:
    """Deterministic in-memory writer (unit tests, dev)."""

    def __init__(self) -> None:
        self._notes: dict[str, str] = {}

    def write_note(self, relative_path: str, content: str) -> str:
        self._notes[relative_path] = content
        return relative_path

    def note(self, relative_path: str) -> str | None:
        return self._notes.get(relative_path)

    def notes(self) -> dict[str, str]:
        return dict(self._notes)


class NullVaultWriter:
    """Unavailable-vault sink that deliberately persists nothing."""

    def write_note(self, relative_path: str, content: str) -> str:
        return relative_path
