"""Obsidian note rendering and the vault writer boundary (architecture §25)."""

from __future__ import annotations

from datetime import UTC, datetime, timedelta
from pathlib import Path
from uuid import UUID

import pytest
from adapters.obsidian import FileVaultWriter, MemoryVaultWriter
from core.domain.enums import SignalDirection
from core.schemas.posttrade import PostTradeReviewRecord
from engines.posttrade.notes import note_path, render_note

from factories import make_posttrade_review, make_trade_metrics

REVIEW_ID = UUID("12345678-1234-4234-8234-123456789abc")


def make_record() -> PostTradeReviewRecord:
    now = datetime(2026, 8, 27, 12, 0, tzinfo=UTC)
    review = make_posttrade_review(now)
    return PostTradeReviewRecord(
        review_id=REVIEW_ID,
        trade_id=review.trade_id,
        instrument_id="EURUSD",
        strategy_id="paper-baseline-001",
        strategy_version="1.0.0",
        direction=SignalDirection.LONG,
        opened_at=now - timedelta(hours=2),
        closed_at=now,
        exit_reason="take_profit",
        metrics=make_trade_metrics(now),
        verdict="SUPPORTED",
        postmortem_completed=True,
        review_payload=review.canonical_dict(),
        created_at=now,
    )


def test_note_path_layout() -> None:
    closed_at = datetime(2026, 8, 27, 12, 0, tzinfo=UTC)
    assert note_path(closed_at, "EURUSD", REVIEW_ID) == (
        "50_Postmortems/2026/EURUSD/2026-08-27-12345678.md"
    )


def test_render_note_frontmatter_and_sections() -> None:
    content = render_note(make_record())
    assert content.startswith("---\n")
    assert "trade_id:" in content
    assert "review_id: 12345678-1234-4234-8234-123456789abc" in content
    assert "# Postmortem — EURUSD LONG" in content
    assert "## Metrics" in content
    assert "## Expected vs actual" in content
    assert "## Signal quality" in content
    assert "## Lessons" in content
    assert "## Trace" in content
    assert "Autogenerated by the OpenTrading post-trade engine" in content
    assert "| R multiple | 1.20R |" in content


def test_memory_vault_writer_round_trip() -> None:
    writer = MemoryVaultWriter()
    writer.write_note("50_Postmortems/2026/EURUSD/a.md", "body")
    assert writer.note("50_Postmortems/2026/EURUSD/a.md") == "body"
    assert writer.notes() == {"50_Postmortems/2026/EURUSD/a.md": "body"}


def test_file_vault_writer_writes_and_reads(tmp_path: Path) -> None:
    writer = FileVaultWriter(tmp_path / "vault")
    path = writer.write_note("50_Postmortems/2026/EURUSD/a.md", "body")
    assert path == "50_Postmortems/2026/EURUSD/a.md"
    assert (tmp_path / "vault" / path).read_text(encoding="utf-8") == "body"


def test_file_vault_writer_rejects_escaping_paths(tmp_path: Path) -> None:
    writer = FileVaultWriter(tmp_path / "vault")
    with pytest.raises(ValueError, match="escapes the vault"):
        writer.write_note("../../etc/passwd", "bad")
