"""Human-readable Obsidian note rendering (architecture §25).

Deterministic markdown with YAML frontmatter — one note per closed trade,
written into the Obsidian vault by a :class:`~adapters.obsidian.vault.VaultWriter`.
Autogenerated notes are marked as such; they never contain secrets (INV-9).
"""

from __future__ import annotations

from datetime import datetime
from uuid import UUID

from core.schemas.posttrade import PostTradeReviewRecord

__all__ = ["note_path", "render_note"]

_NOTE_HEADER = "> Autogenerated by the OpenTrading post-trade engine. Do not edit manually.\n"


def note_path(closed_at: datetime, instrument_id: str, review_id: UUID) -> str:
    """Vault-relative path under the canonical postmortem directory."""
    short = review_id.hex[:8]
    return f"50_Postmortems/{closed_at.year:04d}/{instrument_id}/{closed_at:%Y-%m-%d}-{short}.md"


def render_note(record: PostTradeReviewRecord) -> str:
    """Render the deterministic markdown note for one review."""
    metrics = record.metrics
    review = record.review_payload
    lines: list[str] = ["---"]
    lines.append("generated: true")
    lines.append("authoritative: false")
    lines.append("generator: OpenTrading post-trade engine")
    lines.append("canonical_id_type: review_id")
    lines.append(f"canonical_id: {record.review_id}")
    lines.append(f"trade_id: {record.trade_id}")
    lines.append(f"review_id: {record.review_id}")
    lines.append(f"trace_id: {record.trace_id}")
    lines.append(f"instrument: {record.instrument_id}")
    lines.append(f"direction: {record.direction.value}")
    lines.append(f"opened_at: {record.opened_at.isoformat()}")
    lines.append(f"closed_at: {record.closed_at.isoformat()}")
    lines.append(f"exit_reason: {record.exit_reason}")
    lines.append(f"verdict: {record.verdict}")
    lines.append(f"market_regime: {metrics.market_regime}")
    lines.append("---")
    lines.append("")
    lines.append(f"# Postmortem — {record.instrument_id} {record.direction.value}")
    lines.append("")
    lines.append(_NOTE_HEADER)
    lines.append("")
    lines.append("## Metrics")
    lines.append("")
    lines.append("| Metric | Value |")
    lines.append("| --- | --- |")
    lines.append(f"| Gross PnL | {metrics.pnl_gross} |")
    lines.append(f"| Net PnL | {metrics.pnl_net} |")
    lines.append(f"| Fees | {metrics.fees} |")
    lines.append(f"| Slippage | {metrics.slippage} |")
    lines.append(f"| R multiple | {_fmt(metrics.r_multiple, 'R')} |")
    lines.append(f"| Alpha | {_fmt(metrics.alpha_pct, '%')} |")
    lines.append(f"| MAE | {_fmt(metrics.mae_pct, '%')} |")
    lines.append(f"| MFE | {_fmt(metrics.mfe_pct, '%')} |")
    lines.append(f"| Holding time | {metrics.holding_seconds}s |")
    lines.append(f"| Entry efficiency | {_fmt(metrics.entry_efficiency, '')} |")
    lines.append(f"| Exit efficiency | {_fmt(metrics.exit_efficiency, '')} |")
    lines.append(f"| Prediction error | {_fmt(metrics.prediction_error_pct, '%')} |")
    lines.append("")
    lines.append("## Expected vs actual")
    lines.append("")
    expected_vs_actual = review.get("expected_vs_actual", {})
    if expected_vs_actual:
        for key, value in sorted(expected_vs_actual.items()):
            lines.append(f"- `{key}`: {value}")
    else:
        lines.append("- _(no expected-vs-actual comparison captured)_")
    lines.append("")
    lines.append("## Signal quality")
    lines.append("")
    for quality in review.get("signal_quality", []):
        direction = quality.get("direction") or "absent"
        correct = quality.get("direction_correct")
        lines.append(
            f"- `{quality.get('producer')}`: direction={direction}, "
            f"correct={correct}, brier={_fmt(quality.get('brier_error'), '')}"
        )
    lines.append("")
    lines.append("## Lessons")
    lines.append("")
    lessons = review.get("lessons", [])
    if lessons:
        for lesson in lessons:
            lines.append(f"- {lesson}")
    else:
        lines.append("- _(no lessons distilled)_")
    lines.append("")
    lines.append("## Trace")
    lines.append("")
    lines.append(f"- review: `{record.review_id}`")
    if record.artifact_key:
        lines.append(f"- artifact: `{record.artifact_key}`")
    if record.episode_id:
        lines.append(f"- memory episode: `{record.episode_id}`")
    lines.append("")
    return "\n".join(lines)


def _fmt(value: float | None, suffix: str) -> str:
    if value is None:
        return "n/a"
    if suffix == "R":
        return f"{value:.2f}R"
    if suffix == "%":
        return f"{value:.3f}%"
    return f"{value:.3f}"
