"""Domain layer: canonical enums and state machines (architecture §5-§18)."""

from core.domain.enums import (
    AssetClass,
    CandidateStatus,
    ExecutionState,
    ExperimentStatus,
    MemoryLayer,
    OperatingMode,
    OrderSide,
    OrderState,
    OrderType,
    PositionSide,
    PromotionAction,
    ResearchStatus,
    RiskDecisionType,
    RiskReasonCode,
    SignalDirection,
    StrategyState,
    Timeframe,
    TimeInForce,
    allows_order_submission,
    is_live_mode,
)
from core.domain.state_machines import (
    ORDER_STATE_TRANSITIONS,
    STRATEGY_STATE_TRANSITIONS,
    InvalidStateTransition,
    assert_valid_order_transition,
    assert_valid_strategy_transition,
    is_valid_order_transition,
    is_valid_strategy_transition,
)

__all__ = [
    "ORDER_STATE_TRANSITIONS",
    "STRATEGY_STATE_TRANSITIONS",
    "AssetClass",
    "CandidateStatus",
    "ExecutionState",
    "ExperimentStatus",
    "InvalidStateTransition",
    "MemoryLayer",
    "OperatingMode",
    "OrderSide",
    "OrderState",
    "OrderType",
    "PositionSide",
    "PromotionAction",
    "ResearchStatus",
    "RiskDecisionType",
    "RiskReasonCode",
    "SignalDirection",
    "StrategyState",
    "TimeInForce",
    "Timeframe",
    "allows_order_submission",
    "assert_valid_order_transition",
    "assert_valid_strategy_transition",
    "is_live_mode",
    "is_valid_order_transition",
    "is_valid_strategy_transition",
]
